[package]
name = "lightway-client"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/expressvpn/lightway"
authors = ["lightway-developers@expressvpn.com"]
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["postquantum", "io-uring"]
debug = ["lightway-core/debug"]
postquantum = ["lightway-core/postquantum"]
io-uring = ["lightway-app-utils/io-uring"]

[dependencies]
lightway-core = { workspace = true }
lightway-app-utils = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing-subscriber = { workspace = true}
tracing = { workspace = true }
tokio-stream = { workspace = true, features = ["time"] }
twelf = { workspace = true }
socket2 = { workspace = true }
bytesize = { version = "1.3.0", features = ["serde"] }
libc = "0.2.152"
futures = "0.3.30"
tokio-util = { workspace = true }
ctrlc = { workspace = true }
pnet = { workspace = true }
educe = { workspace = true }

[dev-dependencies]
more-asserts = { workspace = true }
