name: Nightly `cargo deny` checks
on:
  schedule:
    - cron:  '36 3 * * *'
  workflow_dispatch:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
